/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vbarunner_VBAExcel */

#ifndef _Included_com_vbarunner_VBAExcel
#define _Included_com_vbarunner_VBAExcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vbarunner_VBAExcel
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vbarunner_VBAExcel_start
  (JNIEnv *, jobject);

/*
 * Class:     com_vbarunner_VBAExcel
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_vbarunner_VBAExcel_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_vbarunner_VBAExcel
 * Method:    runVBABarcode
 * Signature: (Ljava/lang/String;[I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_vbarunner_VBAExcel_runVBABarcode
  (JNIEnv *, jobject, jstring, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
